# Generated by Django 3.2.8 on 2021-10-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erabiltzailea', models.CharField(max_length=255)),
                ('izena', models.CharField(max_length=255)),
                ('abizena', models.CharField(max_length=255)),
                ('helbidea', models.CharField(max_length=255)),
                ('telefonoa', models.IntegerField()),
                ('nan', models.CharField(max_length=9)),
                ('pasahitza', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Bezeroak',
            },
        ),
        migrations.CreateModel(
            name='Mota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mota_kodea', models.IntegerField()),
                ('izena', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Motak',
            },
        ),
        migrations.CreateModel(
            name='Saskia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saski_kodea', models.CharField(max_length=255)),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.bezeroa')),
            ],
            options={
                'verbose_name_plural': 'Saskiak',
            },
        ),
        migrations.CreateModel(
            name='Produktua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produktu_kodea', models.CharField(max_length=255)),
                ('izena', models.CharField(max_length=255)),
                ('prezioa', models.FloatField()),
                ('irudia', models.CharField(max_length=255)),
                ('iruzkina', models.CharField(max_length=255)),
                ('mota', models.ManyToManyField(to='apiapp.Mota')),
            ],
            options={
                'verbose_name_plural': 'Produktuak',
            },
        ),
        migrations.CreateModel(
            name='Eskaera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produktu_kodea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.produktua')),
                ('saski_kodea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.saskia')),
            ],
            options={
                'verbose_name_plural': 'Eskaerak',
            },
        ),
    ]
