# Generated by Django 3.2.9 on 2021-11-09 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cukysapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezeroa',
            name='antzeko',
            field=models.ManyToManyField(blank=True, related_name='is_antzeko_to', to='cukysapp.Bezeroa'),
        ),
        migrations.CreateModel(
            name='Puntuazioa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuazioa', models.PositiveSmallIntegerField(null=True)),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produktu_kodea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cukysapp.produktua')),
            ],
        ),
    ]
