# Generated by Django 3.2.8 on 2021-10-26 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cukysapp', '0002_auto_20211022_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='saskia',
            name='entrega_data',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saskia',
            name='eskaera_data',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
