# Generated by Django 3.2.9 on 2021-11-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukysapp', '0003_auto_20211109_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produktua',
            name='antzeko',
        ),
        migrations.AddField(
            model_name='bezeroa',
            name='antzeko',
            field=models.ManyToManyField(blank=True, related_name='is_antzeko_to', to='cukysapp.Bezeroa'),
        ),
    ]
