# Generated by Django 3.2.8 on 2021-10-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cukysapp', '0003_auto_20211026_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saskia',
            name='entrega_data',
        ),
        migrations.RemoveField(
            model_name='saskia',
            name='eskaera_data',
        ),
    ]
