# Generated by Django 3.2.9 on 2021-11-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cukysapp', '0004_auto_20211109_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuazioa',
            name='puntuazioa',
        ),
    ]
