# Generated by Django 3.2.8 on 2021-10-26 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cukysapp', '0004_auto_20211026_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezeroa',
            name='emaila',
            field=models.EmailField(default='viguera.alvaro@uni.eus', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saskia',
            name='entrega_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saskia',
            name='eskaera_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
