# Generated by Django 3.2.8 on 2021-11-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cukysapp', '0005_remove_puntuazioa_puntuazioa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntuazioa',
            options={'verbose_name_plural': 'Puntuazioak'},
        ),
    ]
