# Generated by Django 3.2.8 on 2021-11-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukysapp', '0006_alter_puntuazioa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eskaera',
            name='kantitatea',
            field=models.IntegerField(default=0),
        ),
    ]
